# Generated by Django 4.1.1 on 2022-12-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='d_name',
        ),
    ]
